[package]
name = "syshmi-updater"
version = "0.1.0"
edition = "2024"

[dependencies]
google-cloud-storage = "1.5.0"
serde = { version = "1.0.228", features = ["derive"] }
tokio = "1.48.0"
toml = "0.9.10"
